dist: xenial
sudo: required
language: python
before_script:
  # Add an IPv6 config
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == linux ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo -e "\n::1    ip6-localhost\n" >> /etc/hosts';
    fi
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35

install:
- pip install tox
- pip install flake8
- if [ "${TOX_ENV}" == py37 ]; then
    pip install black
  fi
script: 
- tox -e $TOX_ENV
- flake8 .
- if [ "${TOX_ENV}" == py37 ]; then
    black --check . --exclude=.tox
  fi
after_success:
- pip install coveralls
- coveralls
