dist: xenial
sudo: required
language: python


matrix:
  include:
    - python: 3.4
      env: TOX_ENV=py34
      name: "python 3.4 - linux"
    - python: 3.5
      env: TOX_ENV=py35
      name: "python 3.5 - linux"
    - python: 3.6
      env: TOX_ENV=py36
      name: "python 3.6 - linux"
    - python: 3.7
      env: TOX_ENV=py37
      name: "python 3.7 - linux"
    - python: 3.8
      env: TOX_ENV=py38
      name: "python 3.8 - linux"
    - python: 3.7
      env: TOX_ENV=flake8
      name: "flake8 check (linting)"
    - python: 3.7
      env: TOX_ENV=black
      name: "black check (code format)"      


before_script:
  # Add an IPv6 config
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == linux ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo -e "\n::1    ip6-localhost\n" >> /etc/hosts';
    fi


install:
  - python -m pip install --upgrade pip
  - pip install -r requirements-dev.txt


script: 
  - tox -e $TOX_ENV


after_success:
  - pip install coveralls
  - coveralls
