language: python
python: "3.6"
sudo: required
env:
- TOX_ENV=py36
install:
- pip install tox
before_script:
  # Add an IPv6 config
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == linux ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo -e "\n::1    ip6-localhost\n" >> /etc/hosts';
    fi
script: tox -e $TOX_ENV
after_success:
- pip install coveralls
- coveralls
